---
abstract: 'FusionInventory Agent Network Discovery task'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FusionInventory-Agent-Task-NetDiscovery
no_index:
  directory:
    - inc
    - t
requires:
  Net::IP: 0
  Net::NBName: 0
  Net::SNMP: 0
  XML::TreePP: 0.26
  perl: 5.8.0
  threads: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 2.1
