---
abstract: 'Network discovery support for FusionInventory Agent'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FusionInventory-Agent-Task-NetDiscovery
no_index:
  directory:
    - inc
    - t
requires:
  FusionInventory::Agent: 2.0
  Net::IP: 0
  Net::NBName: 0
  Net::SNMP: 0
  Nmap::Parser: 0
  Parallel::ForkManager: 0
  XML::Simple: 0
  perl: 5.6.0
  threads: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 1.2
